identifier: l3i3l0p8t3dea5w3
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: portfolio
homeFolder: /home/user/Área de Trabalho/Backup alterações/portfolio
distFolder: ./dist/portfolio
outDir: /home/user/Área de Trabalho/Backup alterações/portfolio/dist/static
handle404: ''
allowErrorCollect: true
